### ISSUE TITLE
Errors on npm install

### ISSUE THREAD

**Issue by CecileSun** [freedomsponsors/fsstatic2#1]
Hi Tony, 
I tried to set up the environment, but I got lots of errors when I 'npm install', could you help me to fix that?
![npmerrors](https://cloud.githubusercontent.com/assets/9815605/8408848/611d89f8-1eae-11e5-9009-7c2bb9f9006d.png)

What I did was:
1) Install Node.js (sudo apt-get update -> sudo apt-get install nodejs)
2) Install npm (sudo apt-get install npm)
3) Install gulp (sudo npm install -g gulp)
4) npm install (Errors!!)

Thank you!!!

**Comment by tonylampada** [comment]
It seems you're in the wrong directory to run that command (/usr/bin/)
Does [this](https://www.youtube.com/watch?v=rs6fKQRMlTw) help?

**Comment by CecileSun** [comment]
Oh yes! I forgot to cd! Sorry for that! I works well now!
